# Sample Config File for star_yuuki_bot
# Please replace setting options from `libs/config.py`

Yuuki:
  SecurityService: True
  Default_Language: en

LINE:
  Server:
    Host: http://gd2.line.naver.jp
    Command_Path: /lib
    LongPoll_path: /lib

  Account:
    X-Line-Application: LINE_Application_Identification
    X-Line-Access: LINE_Application_AccessKey
    User-Agent: LINE_Application_User-Agent
